[phases.setup]
nixPkgs = ["php82", "php82Extensions.mysqli", "php82Extensions.pdo_mysql", "php82Extensions.mbstring", "php82Extensions.session"]

[phases.build]
cmds = ["cp .php.ini /usr/local/etc/php/conf.d/custom.ini"]

[start]
cmd = "php -S 0.0.0.0:$PORT -t ."
